# Generated by Django 4.1.9 on 2023-06-16 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OPD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='village',
            new_name='DistrictID',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='district',
            new_name='stateID',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='village',
            new_name='DistrictID',
        ),
    ]
