# Generated by Django 4.1.9 on 2023-06-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OPD', '0002_rename_village_city_districtid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='City_name',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='id',
            new_name='Cityid',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='name',
            new_name='District_name',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='id',
            new_name='Districtid',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='id',
            new_name='Doctorid',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='State_name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='id',
            new_name='Stateid',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='name',
            new_name='Village_name',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='id',
            new_name='Villageid',
        ),
    ]
