# Generated by Django 4.1.9 on 2023-06-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPD', '0003_rename_name_city_city_name_rename_id_city_cityid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='id',
        ),
        migrations.AddField(
            model_name='specialty',
            name='specialityID',
            field=models.AutoField(default=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='Cityid',
            field=models.AutoField(default=8000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='district',
            name='Districtid',
            field=models.AutoField(default=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Doctorid',
            field=models.AutoField(default=1200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='Villageid',
            field=models.AutoField(default=2000, primary_key=True, serialize=False),
        ),
    ]
