# Generated by Django 4.1.9 on 2023-06-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPD', '0004_remove_specialty_id_specialty_specialityid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='Cityid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='district',
            name='Districtid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Doctorid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='specialityID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='Villageid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
