# Generated by Django 4.1.9 on 2023-06-17 08:37

import OPD.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OPD', '0005_alter_city_cityid_alter_district_districtid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', OPD.models.CustomAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fh_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=7)),
                ('category', models.CharField(choices=[('GEN', 'General'), ('OBC', 'OBC'), ('SC', 'SC & ST')], max_length=5)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OPD.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OPD.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OPD.state')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OPD.village')),
            ],
        ),
    ]
