# Generated by Django 4.1.9 on 2023-06-17 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OPD', '0006_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='DistrictID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OPD.district'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OPD.city'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OPD.village'),
        ),
        migrations.AlterField(
            model_name='village',
            name='DistrictID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OPD.district'),
        ),
    ]
